name: monopyly
dependencies:
  - coverage=4.5.3
  - flask=1.0.2
  - flask-wtf=0.14.2
  - ipython=7.3.0
  - jupyter=1.0.0
  - matplotlib=3.0.3
  - numpy=1.16.2
  - pip=19.0.3
  - pytest=4.3.0
  - pytest-cov=2.6.1
  - python=3.7.2
  - seaborn=0.9.0
  - setuptools=40.8.0
  - werkzeug=0.16.1
